version: '3'
services:
  app:
    build: .
    tty: true
    volumes:
      - .:/TestingPlayFramework
    ports:
      - 9000:9000
    command: sbt run
    depends_on:
      - database
  database:
    image: "mysql:5.6"
    environment:
      MYSQL_ROOT_PASSWORD: tpf
      MYSQL_DATABASE: tpf
      MYSQL_USER: tpf
      MYSQL_PASSWORD: tpf
    ports:
      - 3306:3306
    expose:
      - 3306
